# Generated by Django 4.1.3 on 2024-10-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("contents", models.BinaryField()),
                ("url", models.TextField(unique=True)),
                ("last_modified", models.DateTimeField()),
                ("when_downloaded", models.DateTimeField()),
            ],
            options={
                "db_table": "Data",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Downloadqueries",
            fields=[
                ("query", models.TextField(primary_key=True, serialize=False)),
                ("last_issued", models.DateTimeField()),
            ],
            options={
                "db_table": "DownloadQueries",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Infos",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("value", models.TextField()),
            ],
            options={
                "db_table": "Infos",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("metadata", models.TextField()),
                ("name", models.TextField(unique=True)),
                ("encoding", models.TextField()),
                ("last_modified", models.DateTimeField()),
            ],
            options={
                "db_table": "Metadata",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField(unique=True)),
                ("language", models.TextField(blank=True, null=True)),
                ("author", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("subject", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Search",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SearchContent",
            fields=[
                ("docid", models.AutoField(primary_key=True, serialize=False)),
                ("c0key", models.TextField(blank=True, null=True)),
                ("c1language", models.TextField(blank=True, null=True)),
                ("c2author", models.TextField(blank=True, null=True)),
                ("c3title", models.TextField(blank=True, null=True)),
                ("c4subject", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Search_content",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SearchSegdir",
            fields=[
                ("level", models.AutoField(primary_key=True, serialize=False)),
                ("idx", models.IntegerField(blank=True, null=True)),
                ("start_block", models.IntegerField(blank=True, null=True)),
                ("leaves_end_block", models.IntegerField(blank=True, null=True)),
                ("end_block", models.IntegerField(blank=True, null=True)),
                ("root", models.BinaryField(blank=True, null=True)),
            ],
            options={
                "db_table": "Search_segdir",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SearchSegments",
            fields=[
                ("blockid", models.AutoField(primary_key=True, serialize=False)),
                ("block", models.BinaryField(blank=True, null=True)),
            ],
            options={
                "db_table": "Search_segments",
                "managed": True,
            },
        ),
    ]
